Module 1
raknoz/FIUBA-algorithms_1 pull request #1
Opened 2020-04-23 23:56 UTC by raknoz

2020-04-24 13:46 UTC, ebarsp commented on module_1/ex_1_10_2.py
> +'''
esto deberia ir debajo de la firma del metodo

2020-04-24 13:48 UTC, ebarsp commented on module_1/ex_1_10_2.py
> +        print(f'el cuadrado de {x} es  { x * x}')
en la cursada tienden a usar el string.format

print("el cuadrado de {} es  {}".format(x, x * x))

2020-04-24 13:54 UTC, ebarsp commented on module_1/ex_1_10_6.py
> +    if(n == 1):
no usamos parentesis en los ifs

2020-04-24 13:56 UTC, ebarsp commented on module_1/ex_1_10_6.py
> +    else:
este else no es necesario.

si ya vieron ifs en clase seguro hablaron que el return hace el retorno directamente al llamado de funcion. por lo cual no continua y al no continuar no es necesario el else

2020-04-24 14:21 UTC, ebarsp commented on module_1/ex_1_10_2.py
> +'''
la idea no es poner la consigna sino qué es lo que hace el metodo. por ejemplo en este caso en particular seria

> metodo que calcula e imprime cuadrados. solicita por pantalla el ingreso de dos numeros enteros y realiza el calculo del cuadrado en el rango excluyente `[primero; segundo)` de numeros enteros entre estos.

2020-04-24 14:22 UTC, ebarsp requested changes
revisar comentarios

2020-04-26 14:53 UTC, raknoz commented on module_1/ex_1_10_2.py
> +'''
Dejo las consignas para saber que es lo que tenía que hacer en esos ejercicios. En los primeros módulos es redundante, pero en los otros se los ejercicios tienen varios puntos conectados.

2020-04-26 15:06 UTC, raknoz commented on module_1/ex_1_10_2.py
> +        print(f'el cuadrado de {x} es  { x * x}')
Leru leru

2020-04-26 20:57 UTC, ebarsp approved these changes

2020-04-30 20:52 UTC, merged