Exam 3
raknoz/FIUBA-algorithms_1 pull request #22
Opened 2020-07-20 22:04 UTC by raknoz

Que la fuerza me acompañe!

2020-08-06 06:10 UTC, ebarsp requested changes
check comments

2020-08-06 06:10 UTC, ebarsp commented on exam_3/Cola.py
> +            self.ultimo = nuevo
veo que en ambos casos estamos haciendo self.ultimo por lo que podriamos sacarlo de ambos ifs y dejarlo al final no?

```
if self.ultimo is not None:
   self.ultimo.prox = nuevo
else:
   self.primero = nuevo
self.ultimo = nuevo
```

2020-08-06 06:10 UTC, ebarsp commented on exam_3/Cola.py
> +        if self.primero is None:
Esto repite funcionalidad, porque si el dia de mañana el validador de cola vacia cambia tendrias que cambiarlo aca tambien.

En cambio si usas `self.esta_vacia(self)` no tendrias el problema.

2020-08-06 06:10 UTC, ebarsp commented on exam_3/IteradorListaEnlazada.py
> +            return str(self.dato)
esta definicion de clase la veo repetida en Cola. Porque reescribirla y no reutilizarla?

2020-08-06 06:10 UTC, ebarsp commented on exam_3/ListaEnlazada.py
> +    def pop(self, i=None):
si `i` es la posicion o index, porque no se llama posicion o index?

2020-08-06 06:10 UTC, ebarsp commented on exam_3/ListaEnlazada.py
> +                n_ant.prox = n_act.prox
es necesario dejarlo dentro de la iteracion? porque si o porque no?

2020-08-06 06:10 UTC, ebarsp commented on exam_3/ListaEnlazada.py
> +    def remove(self, x):
que es x? si es un valor o dato porque no se llama valor o dato?

2020-08-06 06:10 UTC, ebarsp commented on exam_3/Pila.py
> +class Pila:
en mis tiempos(? existia un metodo que te permitia ver el valor del tope de la pila sin necesidad de desapilar

2020-08-06 06:10 UTC, ebarsp commented on exam_3/exam_3.py
> +def rotar_lista_enlazada(lista_e, n):
no está mal. resuelve. pero creo se podria optimizar estas 3 iteraciones que se hacen en 1 sola.

como?
le.rotar(4) -> [5,6,7,8,1,2,3,4]

1. me guardo el puntero de la posicion inicial
2. itero una sola vez la lista

mientras itero:
3. me guardo el puntero a la posicion anterior
4. pregunto si estoy en la posicion de corte n = 4
5. si estoy en la posicion de corte: esa sera la posicion inicial de la lista y a la posicion anterior le quito el proximo

una vez que termino de recorrer la lista deberia tener dos listas [1,2,3,4] [5,6,7,8] y lo unico que deberia hacer es a ese ultimo nodo, el que tiene valor 8, setearle como proximo el puntero inicial que nos guardamos en el primer punto dandome como resultado final [5,6,7,8,1,2,3,4]

validar casos borde

2020-08-06 06:10 UTC, ebarsp commented on exam_3/exam_3.py
> +        resto = resultado % 10 if resultado >= 10 else 0
que sucede en el caso p1 = [6,4,1,1] y p2 = [7,8]?

2020-08-06 06:10 UTC, ebarsp commented on exam_3/exam_3.py
> +    return aux
Entiendo segun el enunciado que se espera una modificacion de la cola dada y no una nueva cola con el resultado

2020-08-15 18:04 UTC, raknoz commented on exam_3/Cola.py
> +            self.ultimo = nuevo
Los archivos Cola.py, Pila.py, ListaEnlazada.py son sacados del apunte. Fue por eso que no se modificaron.

2020-08-15 18:04 UTC, raknoz commented on exam_3/Cola.py
> +        if self.primero is None:
Los archivos Cola.py, Pila.py, ListaEnlazada.py son sacados del apunte. Fue por eso que no se modificaron.

2020-08-15 18:05 UTC, raknoz commented on exam_3/IteradorListaEnlazada.py
> +            return str(self.dato)
Los archivos Cola.py, Pila.py, ListaEnlazada.py,IteradorListaEnlazada.py son sacados del apunte. Fue por eso que no se modificaron.

2020-08-15 18:05 UTC, raknoz commented on exam_3/ListaEnlazada.py
> +    def pop(self, i=None):
Los archivos Cola.py, Pila.py, ListaEnlazada.py,IteradorListaEnlazada.py son sacados del apunte. Fue por eso que no se modificaron.

2020-08-15 18:06 UTC, raknoz commented on exam_3/ListaEnlazada.py
> +                n_ant.prox = n_act.prox
Los archivos Cola.py, Pila.py, ListaEnlazada.py,IteradorListaEnlazada.py son sacados del apunte. Fue por eso que no se modificaron.

2020-08-15 18:06 UTC, raknoz commented on exam_3/ListaEnlazada.py
> +    def remove(self, x):
Los archivos Cola.py, Pila.py, ListaEnlazada.py,IteradorListaEnlazada.py son sacados del apunte. Fue por eso que no se modificaron.

2020-08-15 18:06 UTC, raknoz commented on exam_3/Pila.py
> +class Pila:
Los archivos Cola.py, Pila.py, ListaEnlazada.py,IteradorListaEnlazada.py son sacados del apunte. Fue por eso que no se modificaron.

2020-08-15 18:17 UTC, raknoz commented on exam_3/exam_3.py
> +def rotar_lista_enlazada(lista_e, n):
Si, resuelve me quedo tranquilo. Se pude hacer mejor, seguramente. Voy a agregar el cambio ahora cuando suba las correcciones.

2020-08-15 18:18 UTC, raknoz commented on exam_3/exam_3.py
> +        resto = resultado % 10 if resultado >= 10 else 0
Fue aclarado por mensaje de que las pilas son iguales. De igual modo voy a subir la mejora para el caso de que no sean iguales.

2020-08-15 19:29 UTC, raknoz commented on exam_3/exam_3.py
> +def rotar_lista_enlazada(lista_e, n):
Que pasa en el caso de que n = 9??? Si la lista es de 8 elementos, cuando llegue al final el prox = none y se termina la while.

2020-08-18 21:58 UTC, ebarsp commented on exam_3/exam_3.py
> +def rotar_lista_enlazada(lista_e, n):
Algo que no noté antes es que se pide un **método** y se ejemplifica ademas con `le.rotar(4)`.
Un método a diferencia de una función, pertenece a una clase. Lo que se ve hecho acá es una función.
Cómo nos damos cuenta?
Por el enunciado y por la firma en los ejemplos.
Por ende la corrección seria asumir que estoy en la implementación de lista enlazada, por lo cual solo recibiría el argumento N.

Respecto a que pasa con un n > len(lista):
Toda lista enlazada sabe la cantidad de nodos/elementos que tiene. Por ende usando ese atributo tomas modulo n y obtenes tu n real a desplazarte.

si tengo n = 26 y mi lista es [1,2,3,4,5] (size=5)
en vez de recorrer 5 veces la lista y despues posicionarme en 1, hago `n % size` y el resto que me de es mi posición final.

2020-08-18 22:08 UTC, ebarsp commented on exam_3/exam_3_review.py
> +    while posicion < n_fases:
funca! de igual manera se podia usar un `for posicion in range(len(c_fases))` ya que sé cuando finalizan las iteraciones.

2020-08-18 22:09 UTC, ebarsp commented on exam_3/exam_3_review.py
> +def depurar_fases(c_fases):
solo con fines academicos(? como lo resolverias si se pide implementarlo con una funcion recursiva?

2026-04-08 11:12 UTC, merged