Module 3
raknoz/FIUBA-algorithms_1 pull request #3
Opened 2020-04-23 23:57 UTC by raknoz

2020-04-26 21:09 UTC, ebarsp commented on module_3/ex_3_9_1.py
> +main()
eso no se solicitó. la consigna unicamente pide escribir dos funciones

2020-04-26 21:09 UTC, ebarsp commented on module_3/ex_3_9_2.py
> +    return h, m, s
esto se escribió en el file anterior. deberia importarse y reutilizarse

2020-04-26 21:10 UTC, ebarsp commented on module_3/ex_3_9_2.py
> +    print('Duracion:', ht, ' horas | ', mt, ' minutos | ', st, ' segundos')
esto se puede meter en el main, no es redundante

2020-04-26 21:13 UTC, ebarsp commented on module_3/ex_3_9_2.py
> +    s2 = int(input("¿Cuántos segundos?: "))
veo que esto es practicamente codigo duplicado. lo que haria es una funcion que me lo simplifique.

**Como?**
escribiria una funcion `obtener_horario()` que me devuelva una tupla de h, m, s. Entonces de esta forma podria reutilizar ese codigo y hacer dos llamados a funcion para obtener horario1 y horario2

2020-04-26 21:14 UTC, ebarsp commented on module_3/ex_3_9_2.py
> +    return h, m, s
`from ex_3_9_1 import a_segundos, a_hms`

2020-04-26 21:14 UTC, ebarsp commented on module_3/ex_3_9_3.py
> +procesa_datos([1, 5, -2, -4])
este llamado a funcion no se requirio

2020-04-26 21:27 UTC, ebarsp commented on module_3/ex_3_9_4.py
> +    return (y1 * z2)-(z1 * y2), (z1 * x2)-(x1 * z2), (x1 * y2)-(y1 * x2)
lo que estamos haciendo aca es basicamente multiplicando y calculando la diferencia entre dos vectores.
deberiamos reutilizar codigo..

2020-04-26 21:29 UTC, ebarsp commented on module_3/ex_3_9_4.py
> +main()
esto no se solicitó

2020-04-26 21:31 UTC, ebarsp commented on module_3/ex_3_9_4.py
> +    return suma_norma / 2
esto ya lo estamos haciendo. hay que reutilizar codigo y considerar que un cuadrilatero se forma a partir de dos triangulos 🤔

2020-04-26 21:31 UTC, ebarsp requested changes
revisar comments

2020-04-27 01:42 UTC, raknoz commented on module_3/ex_3_9_4.py
> +    return suma_norma / 2
Mmmm no se cómo resolver eso....

2020-04-27 05:38 UTC, ebarsp commented on module_3/ex_3_9_4.py
> +    return suma_norma / 2
tenes que pensar el cuadrilatero como la composicion de dos triangulos, calcular el area de esos triangulos y sumarlos.

2026-04-08 11:06 UTC, merged