Module 4
raknoz/FIUBA-algorithms_1 pull request #4
Opened 2020-04-23 23:58 UTC by raknoz

2020-04-26 21:32 UTC, ebarsp commented on module_4/ex_4_6_1.py
> +es_primo(6)
esto no se solicito

2020-04-26 21:32 UTC, ebarsp commented on module_4/ex_4_6_2.py
> +print(my_abs(4))
no se solicitó

2020-04-26 21:33 UTC, ebarsp commented on module_4/ex_4_6_3.py
> +dibujar_matriz_identidad(4)
no se solicitó

2020-04-26 21:34 UTC, ebarsp commented on module_4/ex_4_6_3.py
> +        'Salto de linea'
los comentarios de una linea se hacen con `#salto de una linea`

2020-04-26 21:35 UTC, ebarsp commented on module_4/ex_4_6_3.py
> +            if (c == f):
los paréntesis no son necesarios

2020-04-26 21:35 UTC, ebarsp commented on module_4/ex_4_6_2.py
> +    if(num < 0):
los parentesis no son necesarios

2020-04-26 21:37 UTC, ebarsp commented on module_4/ex_4_6_3.py
> +            print(valor, end=' ')
esto se podría resumir con `print("{} \n".format(valor))` de esta forma nos ahorramos el print en blanco de abajo

2020-04-26 21:43 UTC, raknoz commented on module_4/ex_4_6_1.py
> +es_primo(6)
Tenía que probar que funcionaba

2020-04-26 21:43 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +    else:
este else no es necesario ya que cortó en las anteriores bifurcaciones en caso contrario.

2020-04-26 21:44 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +    elif r == 0:
esto no es necesario que sea un elif ya que no existe el else si el if tiene un return. seria simplemente un if

2020-04-26 21:44 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +interseccion(5, 8, 3, -4)
no se solicitó

2020-04-26 21:52 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +    if(y % 400 == 0) or (y % 4 == 0 and y % 100 != 0):
los parentesis no son necesarios. siempre al momento de evaluar de manera logica se van a evaluar primeros los and y posterior los or. por lo que esto haria primero el `y % 400 == 0` y en caso de que sea falsa la condicion haria el `y % 4 == 0 and y % 100 != 0`.

al momento de dividir en terminos por asi decirlo es primero el and que funcionaria como la multiplicacion y el or que seria como la suma.

4 * 4 + 8 -> para resolver esto resolvemos primero la multiplicacion y luego la suma. de forma logica con and y or hacemos lo mismo. 4 and 4 or 8. no resolveriamos jamas el or antes que los and.

por ende esto podria escribirse tranquilamente sin los parentesis. ojo, si te es mas facil de entender esta perfecto dejarlos. pero no esta de mas saber como funciona esta evaluacion logica por si lo ves algun dia sin parentesis

2020-04-26 21:56 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +    if(y % 400 == 0) or (y % 4 == 0 and y % 100 != 0):
esta division de terminos NO significa que si tengo en java una sentencia como la siguiente vaya a ejecutar el and primero:
objeto == null || objeto.isEnabled() && isValid

siempre parte por los OR evalua la primera condicion y si no se cumple evalua la segunda y recien en la segunda va a evaluar los and. esto pasa tanto en python como en java como en c como everywhere

2020-04-26 21:57 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +    else:
ni los returns ni el else son necesarios. basicamente si me veo retornando estados de un boolean dentro de un if significa que podria retornar la condicion del if.

`return y % 400 == 0 or y % 4 == 0 and y % 100 != 0`

2020-04-26 21:59 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +    elif(m == 2 and not es_bisiesto(y) and d > 28):
no son necesarios los elif, deberian ser if simples ya que no existe el else posterior a un return

2020-04-26 22:00 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +    return (contador_dias(m, y) + d)
los parentesis no son necesarios

2020-04-26 22:05 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +DIC_MESES_DIAS = {0:0, 1:31, 2:28, 3:31, 4:30, 5:31, 6:30, 7:31, 8:31, 9:30, 10:31, 11:30, 12:31}
no está mal, está bien. pero contando que son secuenciales y numeros conocidos esto podriamos meterlo en un array no y acceder por su indice.

MESES_DIAS = [0, 31, 28, 31, .....]

2020-04-26 22:08 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +días_entre_fechas(28, 1, 2011, 29, 1, 2012)
no se solicitó

2020-04-26 22:08 UTC, ebarsp commented on module_4/ex_4_6_6.py
> +dia_de_la_semana(1)
no se solicitó

2020-04-26 22:21 UTC, ebarsp commented on module_4/ex_4_6_7.py
> +#print(numeros_romanos(1999))
no se solicitó

2020-04-26 22:22 UTC, ebarsp commented on module_4/ex_4_6_7.py
> +
falta documentacion de la funcion

2020-04-26 22:22 UTC, raknoz commented on module_4/ex_4_6_7.py
> +
Nunca lo terminé jajaja

2020-04-26 22:24 UTC, ebarsp commented on module_4/ex_4_6_8.py
> +    return 'Piscis'
la idea es evitar el choclo de ifs anidados. hay que pensar una solucion que contemple esto.

2020-04-26 22:25 UTC, ebarsp requested changes
revisar comments

2020-05-04 22:05 UTC, raknoz commented on module_4/ex_4_6_8.py
> +    return 'Piscis'
Encontré una solución re fruta, pero que anda, no la hubiera pensado así ni en pedo jajaja

2020-05-07 18:01 UTC, ebarsp commented on module_4/ex_4_6_7.py
> +def numeros_romanos(num):
no tengo idea que hace esta funcion

2020-05-07 18:03 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +        Función que retorna True o False si un año es o no bisiesto.
esta es la funcion que "valida si un año es bisiesto"

2020-05-07 18:04 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +def valida_bisiesto(y):
esta funcion no esta validando de por si, sola mente imprime un mensaje u otro si es bisiesto

2020-05-07 18:04 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +    x = (-1) * (b / (2 * a))
esta variable x esta demas tranquilamente podemos retornar todo el contenido de x

2020-05-07 18:05 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +    if (a > 0):
estos parentesis estan demas

2020-05-07 18:05 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +    #a == 0
estos comentarios no aportan nada

2020-05-07 18:06 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +    x1 = (calular_vertice_x(a, b, c) + ((evalua_raiz(a, b, c)** 0.2)/(2*a)))
los primeros parentesis no son necesarios

`calular_vertice_x(a, b, c) + ((evalua_raiz(a, b, c)** 0.2)/(2*a))`

2020-05-07 18:06 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +    return y
same

2020-05-07 18:06 UTC, ebarsp commented on module_4/ex_4_6_4.py
> +    x2 = (calular_vertice_x(a, b, c) - ((evalua_raiz(a, b, c)** 0.2)/(2*a)))
same

2020-05-07 18:10 UTC, ebarsp commented on module_4/ex_4_6_5.py
> +    if m != 2 and d > MESES_DIAS[m]:
siendo este el ultimo if y el retorno de la funcion es boolean podriamos retornar la condicion, no?

`return not (m != 2 and d > MESES_DIAS[m])`

lo negue porque si la condicion era True vos devolvias False

2020-05-07 18:12 UTC, ebarsp commented on module_4/ex_4_6_8.py
> +    return signo[m]
👍

2020-05-10 17:18 UTC, raknoz commented on module_4/ex_4_6_4.py
> +    #a == 0
Eh si, es para saber que significa el if abajo. Hice el refactor (post vieja comparación) y cómo para entender que significa lo puse cómo comentario.

2026-04-08 11:07 UTC, merged